### PR TITLE
Adds filtering and sorting to meal list

### PR DESCRIPTION
**Pull request by BarrsX**
IMG_6109
IMG_6110

### CODE REVIEW

**Comment by jeremiahbaclig** [comment]
Why not keep the drawer in case we want to add more to it later? You can just remove the sort from it, proabably. The randomize we can rework with the home button and all that as well so they're not duplicate actions. Then we can add a settings Placeholder() so it's not so empty if that's a concern

**Comment by jeremiahbaclig** [comment]
Might need another TODO here to render the items underneath the PopMenuButton too

**Comment by BarrsX** [comment]
> Why not keep the drawer in case we want to add more to it later? You can just remove the sort from it, proabably. The randomize we can rework with the home button and all that as well so they're not duplicate actions. Then we can add a settings Placeholder() so it's not so empty if that's a concern

The home button does a randomize, and yeah my main thought was putting the home button on the right, so it stays the same on the recipe screen in case someone goes on a string of related recipes they can go home quickly, but I'm not sure how it looks on the right. Then I just kept it off to think of more ideas on having a drawer or something. Kinda thinking of putting a button for a drawer on the right where we can add future pages and stuff

**Comment by jeremiahbaclig** [comment]
> > Why not keep the drawer in case we want to add more to it later? You can just remove the sort from it, proabably. The randomize we can rework with the home button and all that as well so they're not duplicate actions. Then we can add a settings Placeholder() so it's not so empty if that's a concern
> 
> 
> 
> The home button does a randomize, and yeah my main thought was putting the home button on the right, so it stays the same on the recipe screen in case someone goes on a string of related recipes they can go home quickly, but I'm not sure how it looks on the right. Then I just kept it off to think of more ideas on having a drawer or something. Kinda thinking of putting a button for a drawer on the right where we can add future pages and stuff 

Right, I'm not sure how it'll look without designs. Usually they would be on the left tho, but maybe what we need is a persisting navbar and then the back button will be below it on the recipe screen. All in all it's cool, just didn't want to tear out code and then add it back later

**Comment by BarrsX** [comment]
0194660D-2B5E-48E4-A88A-2BAAAB9278FB
82EC2BE5-2E8B-49EE-B811-543A631B7D27

Changed to redAccent, lmk the vibes Minggy

**Comment by jeremiahbaclig** [comment]
We can always change it if we get a color blind dev 🤞

**Review by jeremiahbaclig — APPROVED** [review]

**Pull request merged**
